[mgr]
linemode = "size"
prepend_keymap = [
	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]


[opener]
music = [{ run = 'elisa "$@"', orphan = true, for = "unix" }]
image = [{ run = 'feh "$@"', orphan = true, for = "unix" }]

[open]
prepend_rules = [
	{ mime = "audio/*", use = "music" },
	{ mime = "image/*", use = "image" },
]
