[mgr]
linemode = "size"


[opener]
music = [{ run = 'elisa "$@"', orphan = true, for = "unix" }]
image = [{ run = 'feh "$@"', orphan = true, for = "unix" }]
3dprint = [{ run = 'bambu-studio "$@"', orphan = true, for = "unix" }]
video = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
	{ run = 'ghb "$@"', orphan = true, for = "unix", desc = "Handbrake" },
]
mkv = [
	{ run = 'mkvtoolnix-gui "$@"', orphan = true, for = "unix", desc = "MKVToolNix" },
]
docs = [{ run = 'okular "$@"', orphan = true, for = "unix" }]
nvim = [{ run = 'nvim "$@"', block = true, for = "unix" }]
archive = [{ run = 'ark "$@"', orphan = true, for = "unix" }]


[open]
prepend_rules = [
	{ mime = "audio/*", use = "music" },
	{ mime = "image/*", use = "image" },
	{ url = "*.3mf", use = "3dprint" },
	{ url = "*.cbz", use = "docs" },
	{ mime = "video/*", use = "video" },
]

append_rules = [
	{ mime = "video/matroska", use = "mkv" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "text/*", use = "nvim" },
]


[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git" 

# piper
[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_previewers]]
mime = "application/sqlite3"
run  = 'piper -- sqlite3 "$1" ".schema --indent"'

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'
